# Generated by Django 5.1.6 on 2025-02-22 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediatheque', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planification',
            name='medicament_id',
        ),
        migrations.AddField(
            model_name='planification',
            name='medicament',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.DeleteModel(
            name='Medicament',
        ),
    ]
